### ISSUE TITLE
Using exit-code adds semicolon in. Breaks scripts

### ISSUE THREAD

**Issue by brian-mcnamara** [heroku/heroku-run#51]
When ever I call the run command passing in -x (or --exit-code). It appears to add a semicolon which does not seem to be parsed correctly over in the dyno.

Getting:
```bash
heroku run -x -a myApp --type=worker -- node test.js
Running node test.js on ⬢ MyApp... up, worker.3465 (Private-M)
 ▸    Warning: Dynos can take up to a few minutes to be provisioned in Private Spaces.
module.js:549
    throw err;
    ^

Error: Cannot find module '/home/test.js;'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
 ▸    No exit code returned
```

Or even better:

```bash
heroku run -x -a myApp --type=worker bash                                   
Running bash on ⬢ myApp... up, worker.6364 (Private-M)
 ▸    Warning: Dynos can take up to a few minutes to be provisioned in Private Spaces.
FATA exec: "bash;": executable file not found in $PATH 
 ▸    No exit code returned
```

**Comment by jdxcode** [comment]
Are you using docker for something? This doesn't appear to be a standard dyno.

**Comment by jdxcode** [comment]
The CLI seems to work fine for me doing this with container registry. My guess is something else is going on here with the docker image (possibly that `bash` isn't on the `PATH`). Would you mind submitting a support ticket?

**Comment by brian-mcnamara** [comment]
Will do. Ill close this for now. Seems like its not an issue with the CLI.
